export const enum LeaveApplicationStatus {
  APPLIED = 'APPLIED',

  ACCEPTED_BY_FIRST_AUTHORITY = 'ACCEPTED_BY_FIRST_AUTHORITY',

  REJECTED_BY_FIRST_AUTHORITY = 'REJECTED_BY_FIRST_AUTHORITY',

  ACCEPTED = 'ACCEPTED',

  REJECTED = 'REJECTED',
}
