export const enum LeaveTypeName {
  CASUAL_LEAVE = 'CASUAL_LEAVE',

  MEDICAL_LEAVE = 'MEDICAL_LEAVE',

  EARNED_LEAVE = 'EARNED_LEAVE',

  MATERNITY_LEAVE = 'MATERNITY_LEAVE',

  DUTY_LEAVE = 'DUTY_LEAVE',
}
