export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  WEEKEND_ADMIN = 'ROLE_WEEKEND_ADMIN',
  WEEKEND_MANAGER = 'ROLE_WEEKEND_MANAGER',
  HOLIDAY_ADMIN = 'ROLE_HOLIDAY_ADMIN',
  HOLIDAY_MANAGER = 'ROLE_HOLIDAY_MANAGER',
  ATTENDANCE_ADMIN = 'ROLE_ATTENDANCE_ADMIN',
  ATTENDANCE_MANAGER = 'ROLE_ATTENDANCE_MANAGER',
  LEAVE_ADMIN = 'ROLE_LEAVE_ADMIN',
  LEAVE_MANAGER = 'ROLE_LEAVE_MANAGER',
  LEAVE_USER = 'ROLE_LEAVE_USER',
}
