export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  WEEKEND_ADMIN = 'ROLE_WEEKEND_ADMIN',
  WEEKEND_MANAGER = 'ROLE_WEEKEND_MANAGER',
  HOLIDAY_ADMIN = 'ROLE_HOLIDAY_ADMIN',
  HOLIDAY_MANAGER = 'ROLE_HOLIDAY_MANAGER',
}
